### ISSUE TITLE
数据是从哪里爬的？

### ISSUE THREAD

**Issue by xingyibiao** [klren0312/purineSearchApp#1]
我自己想自己做个app/小程序，不知道你这个数据是哪里爬的？可以参考一下嘛？谢谢啦

**Comment by klren0312** [comment]
手动录的 你信吗

**Comment by wangdi1024** [comment]
> 我自己想自己做个app/小程序，不知道你这个数据是哪里爬的？可以参考一下嘛？谢谢啦

你那个利用gulp吧svg转iconfont是怎么弄的，下载了代码没看明白，能不能指点一下，谢谢啦

**Comment by klren0312** [comment]
并没有使用gulp, 我手动复制的, 然后指定相应的class
https://github.com/klren0312/purineSearchApp/blob/master/components/icon.wxss

![image](https://user-images.githubusercontent.com/10903843/118796313-13ce6800-b8ce-11eb-9487-1efdbe77ab32.png)

![image](https://user-images.githubusercontent.com/10903843/118796511-44160680-b8ce-11eb-8590-b0b1b0a69f18.png)

**Comment by wangdi1024** [comment]
明白了，谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月19日(周三) 晚上6:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [klren0312/purineSearchApp] 数据是从哪里爬的？ (#1)




 
并没有使用gulp, 我手动复制的, 然后指定相应的class

**Comment by klren0312** [comment]
> 我自己想自己做个app/小程序，不知道你这个数据是哪里爬的？可以参考一下嘛？谢谢啦

爬虫已更新
